version: '3.8'
services:
  app:
    build: .
    container_name: app-upload-ctic
    ports:
      - "${PORT_APP}:${PORT_APP}"
    environment:
      - NODE_ENV=development
      - NOME_APP=${NOME_APP}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      app_network:
        ipv4_address: 172.18.1.12

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
