version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_test
    ports:
      - "8085:8085"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development


# docker-compose -f docker-compose_test.yml up